#if !defined(DK_MACROS_H)
#define DK_MACROS_H

static int WINDOW_WIDTH = 1080;
static int WINDOW_HEIGHT = 720;

#define GRID_CELL_SIZE 10

// #define GRID_WIDTH (WINDOW_WIDTH - 200) / GRID_CELL_SIZE
// #define GRID_HEIGHT (WINDOW_HEIGHT - 200) / GRID_CELL_SIZE

#define GRID_WIDTH 72
#define GRID_HEIGHT 52

#define FULLSCREEN 0

#define GRID_CELL_EMPTY 0
#define GRID_CELL_FILLED 1

#define GRID_CELL_COLOR_EMPTY C64_WHITE


#endif // DK_MACROS_H
